config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :books
  resources :payments
  resources :home
  # root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    has_one :user
end

app/models/supplier.rb
class Supplier < ApplicationRecord
    has_one :account
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :set_book, only: %i[ show edit update destroy ]

  def index
    @books = Book.all

    @book = Book.new
  end

  def show
  end

  # GET /books/new
  def new
    @book = Book.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /books/1/edit
  def edit
  end

  def create
    @book = current_user.books.new(book_params)
    respond_to do |format|
      if @book.save
        format.html {redirect_to book_url(@book), notice: "Book was successfully created."}
        format.js
      else
      render :new, status: :unprocessable_entity
      end
    end
  end

  def update
      if @book.update(book_params)
        redirect_to book_url(@book), notice: "Book was successfully updated." 
      else
       render :edit, status: :unprocessable_entity 
      end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy
     redirect_to books_url, notice: "Book was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    def book_params
      params.require(:book).permit(:title )
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
    def new
    end
    
    def create
      customer = Stripe::Customer.create({
        :email => params[:stripeEmail],
        :source => params[:stripeToken]
      })
      
      charge = Stripe::Charge.create({
        :customer => customer.id,
        :amount => 500,
        :description => 'Description of your product',
        :currency => 'pkr'
      })
    
      rescue Stripe::CardError => e
        flash[:error] = e.message
        redirect_to new_payment_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/books/_book.html.erb
<tr>
  <td><%=book.title %></td>
</tr>
 <tr>
  <td><%= link_to 'Show', book_path(book) %></td>
  <td><%= link_to 'Edit', edit_book_path(book) %></td>
  <td><%= link_to 'Destroy', book_path(book), method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/books/_form.html.erb
<%= form_for @book, remote: true do |form| %>

  <div class="actions">
    <%= form.label :title, for: 'book_name' %><br/>
    <%= form.text_field :title, required: true, id: 'book_name' %>
    <%= form.submit %>
  </div>
<% end %>

app/views/books/_modal.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">x</button>
  <h4 class="modal-title" id="myModalLabel">Modal title</h4>
</div>
<div class="modal-body">
  *Modal content comes here*

  <%= render 'form', book: @book %>
</div>
<div class="modal-footer">
  <button class="btn btn-primary">Save</button>
</div>

app/views/books/create.js.erb
var body = document.getElementById("books");
body.innerHTML = "<%= j render @book %>" + body.innerHTML

var input = document.getElementById("book_name");
input.value = '';
input.focus();

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= form_for @book do |form| %>

  <div class="actions">
    <%= form.label :title %><br/>
    <%= form.text_field :title, required: true %>
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Show', book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<%# <%= render 'form', book: @book %> 

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id='books'>
    <%= render @books%>
  </tbody>
</table>

<br>

<%# <%= link_to 'New Book', new_book_path %> 


<%= link_to 'New Book', new_book_path,  {:remote => true, 'data-bs-toggle' =>  "modal", 'data-bs-target' => '#modal-window', class: 'btn btn-primary btn-lg'}  %>
<div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content"></div>
  </div>
</div>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/new.js.erb
$("#modal-window").find(".modal-content").html("<%= j render 'modal' %>");
$("#modal-window").modal();

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>
<%=@book.title %>
<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
 <% if user_signed_in? %>
<li><%= link_to "Logout", destroy_user_session_path, :method => :delete, :class => "btn btn-primary btn-lg" %></li>
<li><%= link_to "Create Book", new_user_book_path, :method => :get, :class => "btn btn-primary btn-lg" %></li>
 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/payments/new.html.erb
<%= form_tag payments_path do %>
  <label class="amount">
      <span>Amount: 5.00</span>
  </label>

  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-description="A month's subscription"
    data-amount="500"
    data-locale="auto">
  </script>
<% end %>